server:
  port: 8901
spring:
  application:
    name: multi-data-source
db:
  mysql:
    datasource:
      jdbc-url: jdbc:mysql://127.0.0.1:3306/test_db
      username: root
      password: 12345
      driverClassName: com.mysql.jdbc.Driver
  postgres:
    datasource:
      url: jdbc:postgresql://127.0.0.1:5432/postgres
      username: postgres
      password: 12345
      driverClassName: org.postgresql.Driver