server:
  port: 8901
spring:
  application:
    name: multi-data-source
mysql:
  datasource:
    url: jdbc:mysql://localhost:3306/classicmodels
    username: root
    password: 12345
postgres:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 12345
